name: Build and Push image
on:
  workflow_dispatch:
  schedule:
    - cron: "42 2 * * 1"
  push:
    branches:
      - main
    paths:
      - 'docker/**'
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Run script
        run: |
          cd ${{ github.workspace }}
          ./build-push.sh